seed: 42

device: ['cuda']

data_sets:
  create_new: False
  split_fraction_train_rest: 0.75
  split_fraction_val_test: 0.5
  root_dir: '/media/dysk/student2/mammografia/Mammografie'
  file_dir: '/media/dysk/student2/mammografia/Zapisy/stats_pickle'
  dataloader_path: /media/dysk/student2/mammografia/Zapisy/data_loader.pth
  dataloader_sizes: '/media/dysk/student2/mammografia/Zapisy/data_loader_sizes.pth'
  image_view: ['CC', 'MLO']
  patch_size: 224
  bag_size_train: 100
  bag_size_val_test: 600
  overlap_train_val: 0.5
  overlap_val_test: 0.5

training_plan:
 
  architectures:
    names: 'gmil'
  
  parameters:
    batch_size: 1
    lr: [0.001]
    wd: [0.001]
    epochs: [1]

  criterion: 'bce'

  optim_name: 'sgd'

  scheduler:
    name: 'lin'
    step_size: 50
    gamma: 0.9
